main:
  - name: 'Home'
    pageRef: '/'
    weight: 10
#  - name: 'Services'
#    pageRef: '/services'
#    weight: 20
#  - name: 'How We Work'
#    pageRef: '/how-we-work'
#    weight: 30
#  - name: 'Blog'
#    pageRef: '/posts'
#    weight: 80
  - name: 'Contact'
    pageRef: '/contact'
    weight: 90
footer:
  - name: 'Home'
    pageRef: '/'
    weight: 10
#  - name: 'FAQ'
#    pageRef: '/faq'
#    weight: 20
  - name: 'Contact'
    pageRef: '/contact'
    weight: 20
  - name: 'Imprint'
    pageRef: '/imprint'
    weight: 80
  - name: 'Privacy'
    pageRef: '/privacy'
    weight: 90